/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fileProccessing
import java.io.File
import java.util.Scanner

class App {
}

val people: MutableList<Person> = ArrayList()

class Reader(url:String){
    //We would neeed to read a given adress and then create objects based on what we can find and seperate the
    val readStream = File(url);
    val scanner = Scanner(readStream);

    fun readLine(){
        while(scanner.hasNext()){
            var next = scanner.nextLine();
            if(next == "Person"){
                var nameLine = scanner.nextLine();//Following line:
                var array:Array<String> = nameLine.split(":").toTypedArray();
                if(array[0].equals("name")){
                    //We want to get rid of the "" around the name
                    var name = array[1];
                   // var cleanName = name.subString(1,name.size()-1);

                    var ageLine = scanner.nextLine();
                    var ageArray = ageLine.split(":").toTypedArray();
                    if(ageArray[0].equals("age")){
                        val age = ageArray[1].toInt();
                        val person = Person(name,age)
                        people.add(person);
                    }
                }
                }
        }
    }
}

class Person(val name:String,val age:Int){
    init{
        println("My name is $name");
        println("My age is $age");
    }
}

fun main(args: Array<String>) {    //We need a file reader to be able to read lines take them in an an input.
    val reader = Reader("C:\\Users\\filip\\Desktop\\Random.txt");
    reader.readLine();
    println("NUMBER OF PEOPLE: ${people.size}")
}
